version: "3.7"
services:
  application:
    image: BOILERPLATE:1.0
    build:
      context: .
      args:
        app_version: 1.0
    environment:
      - BOILERPLATE_SERVER_PORT=10000
      - BOILERPLATE_SERVER_HOST=0.0.0.0
    ports:
      - 9000:10000


